name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions: read-all

jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24
      with:
        egress-policy: audit
    - name: Checkout repository
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      with:
        submodules: 'recursive'
    - name: Build
      run: |
        mkdir build && cd build
        cmake -G 'Unix Makefiles' ..
        cmake --build .
    - name: GET Google
      run: build/tool/msh3app www.google.com
    - name: GET Cloudflare
      run: build/tool/msh3app www.cloudflare.com
